-- The Google saved lists, as far as they could be located.
--
-- Source: data/google-*.csv, scraped from the three shared lists. Generated by
-- scripts/import-saved-places.mjs with a city anchor per list.
--
-- 28 of 83 rows made it. The rest are at the bottom with a reason, and split
-- three ways:
--
--   * closed, or not food — filtered on Google's own category, correctly out
--   * no match in OpenStreetMap — the honest majority. OSM does not carry most
--     newer small restaurants, and an unbounded name search returns the wrong
--     continent rather than nothing. Google Takeout exports these with exact
--     coordinates; see the README.
--   * an unrecognised category — a judgement call, left for you
--
-- Categories come from Google's own place type. Slugs are derived from the name
-- with no random suffix, so re-running after a Takeout import cannot duplicate.
--
-- Safe to re-run: conflicts on slug.

insert into places (slug, name, address, city, neighborhood, country, categories, lat, lng) values
('double-black', 'Double Black', '925 Cole Street', 'San Francisco', 'Cole Valley', 'United States', '{coffee}', 37.7653739, -122.450038),
  ('the-laundromat-sf', 'The Laundromat SF', '517 O''Farrell Street', 'San Francisco', 'Little Saigon', 'United States', '{lunch,dinner}', 37.7856461, -122.4133687),
  ('pang', 'Pàng', '1309 9th Avenue', 'San Francisco', 'Richmond District', 'United States', '{lunch,dinner}', 37.7637661, -122.4664577),
  ('starlite', 'Starlite', '450 Powell Street', 'San Francisco', 'Union Square', 'United States', '{bar}', 37.7889604, -122.4083142),
  ('agrodolce-provisions', 'Agrodolce Provisions', '1016 Bryant Street', 'San Francisco', 'West SoMa', 'United States', '{lunch,dinner}', 37.7723008, -122.4076305),
  ('chisai-sushi-club', 'Chīsai Sushi Club', '3369 Mission Street', 'San Francisco', 'Mission', 'United States', '{lunch,dinner}', 37.7427191, -122.4215785),
  ('shoji', 'Shoji', '140 New Montgomery Street', 'San Francisco', 'Transbay', 'United States', '{bar}', 37.7866435, -122.3997471),
  ('chocolate-covered', 'Chocolate Covered', '4069 24th Street', 'San Francisco', 'Mission', 'United States', '{dessert}', 37.7512428, -122.4333237),
  ('valley', 'Valley', '755 Ashbury Street', 'San Francisco', 'Cole Valley', 'United States', '{lunch,dinner}', 37.7681157, -122.4469477),
  ('pasta-supply-co', 'Pasta Supply Co', '236 Clement Street', 'San Francisco', 'Jordan Park', 'United States', '{lunch,dinner}', 37.7832102, -122.4617661),
  ('saru-handroll-bar', 'Saru Handroll Bar', '2206 Polk Street', 'San Francisco', 'Russian Hill', 'United States', '{lunch,dinner}', 37.7971198, -122.4218918),
  ('routier', 'Routier', '3920B 24th Street', 'San Francisco', 'Mission', 'United States', '{lunch,dinner}', 37.7516237, -122.4302335),
  ('true-laurel', 'True Laurel', '753 Alabama Street', 'San Francisco', 'Mission', 'United States', '{bar}', 37.7594967, -122.4114886),
  ('hey-neighbor-cafe', 'Hey Neighbor Cafe', '2 Burrows Street', 'San Francisco', 'Bayview District', 'United States', '{coffee}', 37.7290443, -122.4037642),
('souraji', 'SourAji', '23 Avenue B', 'New York', 'Alphabet City', 'United States', '{lunch,dinner}', 40.7222329, -73.9831367),
  ('lil-sweet-treat', 'lil sweet treat', '150 2nd Avenue', 'New York', 'East Village', 'United States', '{dessert}', 40.7293522, -73.9868971),
  ('bobby-vans', 'Bobby Van''s', 'Exchange Place', 'New York', 'Financial District', 'United States', '{lunch,dinner}', 40.7061255, -74.0110467),
  ('grand-banks', 'Grand Banks', 'Pier 26 Tide Deck', 'New York', 'Manhattan', 'United States', '{lunch,dinner}', 40.7202788, -74.0159252),
  ('naks', 'Naks', '1st Avenue', 'New York', 'East Village', 'United States', '{lunch,dinner}', 40.7302931, -73.9835696),
  ('apotheke-chinatown', 'Apotheke Chinatown', 'Canal Street', 'New York', 'Five Points', 'United States', '{bar}', 40.7162886, -73.9967834),
  ('chicha-san-chen', 'Chicha San Chen', '72 Bayard Street', 'New York', 'Five Points', 'United States', '{tea}', 40.7156257, -73.9982259),
  ('great-ny-noodletown', 'Great NY Noodletown', '28 Bowery', 'New York', 'Five Points', 'United States', '{lunch,dinner}', 40.7149725, -73.9970927),
  ('paulie-gees-slice-shop', 'Paulie Gee''s Slice Shop', '110 Franklin Street', 'New York', 'Greenpoint', 'United States', '{lunch,dinner}', 40.7283593, -73.9571898),
  ('taqueria-ramirez', 'Taqueria Ramirez', '94 Franklin Street', 'New York', 'Greenpoint', 'United States', '{lunch,dinner}', 40.7278816, -73.9569597),
  ('bakeri', 'Bakeri', '150 Wythe Avenue', 'New York', 'Brooklyn', 'United States', '{bakery}', 40.7200059, -73.9600762),
  ('sorate', 'Sorate', '103 Sullivan Street', 'New York', 'University Village', 'United States', '{tea}', 40.7256521, -74.0028846),
  ('supermoon-bakehouse', 'Supermoon Bakehouse', '120 Rivington Street', 'New York', 'Lower East Side', 'United States', '{bakery}', 40.7198311, -73.9872341),
('hardware-coffee-co', 'Hardware Coffee Co.', '900 North Point Street', 'San Francisco', 'Fisherman''s Wharf', 'United States', '{coffee,breakfast}', 37.8058477, -122.4229027)
on conflict (slug) do nothing;

-- ---------------------------------------------------------------------------
-- Not imported
-- ---------------------------------------------------------------------------
--   [SF Food List] Tokyo Cream — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] 680A 2nd St — unrecognised category "La Kalidad" — food? add it to scripts/google-categories.mjs
--   [SF Food List] Golden Sardine — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Hilda's Mart & Bake Shop — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Constance Tea & Matcha — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Iggy's Place — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] TBD izakaya — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Joodooboo — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Roosters Peruvian Rotisserie — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] 35316 Ramsgate Rd — place no longer exists
--   [SF Food List] Café Thuma — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] The Dead Fish — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Kolaj — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Jilli SF — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Daughter Thai Kitchen — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] MirrorMe Self-Portrait Photo Studio — not food (Photography studio)
--   [SF Food List] Fournée Bakery — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Bake Sum — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Alexander's Patisserie — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Kuidaore Handroll Bar — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Bluegrain Sandwich Market — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Twelvemonth — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Malibu Farm Tiburon — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Cultured Pickle Shop — unrecognised category "Natural goods store" — food? add it to scripts/google-categories.mjs
--   [SF Food List] Lokma — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Verjus — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] SHOWA Le Gourmet Tonkatsu — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Kuma on Valencia — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Patio Filipino — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Yoki Sushi — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Komeya No Bento — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Lost Resort — no coordinates in the export and no match in OpenStreetMap
--   [SF Food List] Alnico — permanently closed
--   [New York] Richaud Petite Bakery — no coordinates in the export and no match in OpenStreetMap
--   [New York] Nori Shinn — no coordinates in the export and no match in OpenStreetMap
--   [New York] Nin Hao — no coordinates in the export and no match in OpenStreetMap
--   [New York] Hani’s bakery + café — no coordinates in the export and no match in OpenStreetMap
--   [New York] Sushi Tokoro the handroll bar — no coordinates in the export and no match in OpenStreetMap
--   [New York] Nudie Jeans Co. — not food (Jeans shop)
--   [New York] On Store NYC Lafayette — not food (Sportswear store)
--   [New York] Lucky Cat — no coordinates in the export and no match in OpenStreetMap
--   [New York] BINONDO by Kabisera — no coordinates in the export and no match in OpenStreetMap
--   [New York] Lai Rai — no coordinates in the export and no match in OpenStreetMap
--   [New York] La Cabra Bakery — no coordinates in the export and no match in OpenStreetMap
--   [New York] Carhartt WIP Store New York — not food (Clothing store)
--   [New York] Lili and Cata | Non-toxic Nail Spa — not food (Nail salon)
--   [New York] Industry of All Nations — not food (Clothing store)
--   [New York] BAGGU Brooklyn — not food (Fashion accessories store)
--   [New York] Gentle Monster New York — temporarily closed
--   [New York] Nudie Jeans Co. — not food (Jeans shop)
--   [New York] WORD — not food (Book store)
--   [New York] 70 Greenpoint Ave — no category from Google
--   [New York] Sama Street — permanently closed
--   [Cafes and Matcha] Hilda's Mart & Bake Shop — no coordinates in the export and no match in OpenStreetMap
--   [Cafes and Matcha] Side Characters — no coordinates in the export and no match in OpenStreetMap
